version: "3.8"

services:
  postgres:
    image: postgres
    env_file: ./.env
    environment:
      POSTGRES_PASSWORD: $DB_PASSWORD
      POSTGRES_USER: $DB_USER
      POSTGRES_DB: $DB_DATABASE
    ports:
      - $DB_PORT_LOCAL:$DB_PORT
  server:
    env_file: ./.env
    build: ./server
    ports:
      - $SERVER_PORT:$SERVER_PORT
  client:
    env_file: ./.env
    build: ./client
    ports:
      - $CLIENT_PORT:$CLIENT_PORT

